# Generated by Django 3.2 on 2021-10-10 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.CharField(max_length=70)),
                ('password', models.CharField(max_length=20)),
                ('massage', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
    ]
