# Generated by Django 3.2 on 2021-10-12 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_user_profile_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='linkedIn_url',
            field=models.CharField(default='', max_length=10000),
        ),
    ]
